name: Project CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: make test
      - name: run lint
        run: make lint